version: '3.8'
services:
  my-app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    ports:
      - "8080:8080"
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"