---
- name: Deploy Docker Container on EC2 Server
  hosts: aws_ec2
  become: yes
  gather_facts: yes

  vars_files:
    - ec2-vars.yaml

  handlers:
    - name: restart docker
      systemd:
        name: docker
        state: restarted

  tasks:
    - name: Make sure all packages are up to date
      yum:
        name: '*'
        state: latest
        update_cache: yes
      tags: ['packages']
    
    - name: Ensure Docker and Python3 are installed
      yum:
        name: 
          - python3
          - python3-pip
          - docker
        state: present
      tags: ['packages']
    
    # - name: Install Python Docker SDK (required by Ansible)
    #   pip:
    #     name: 
    #       - docker
    #     executable: pip3
    #   tags: ['packages']

    - name: Install Docker Compose v2 plugin
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-{{ ansible_facts['architecture'] }}"
        dest: /usr/libexec/docker/cli-plugins/docker-compose
        mode: '0755'
      tags: ['packages']

    - name: Verify docker-compose installation
      command: docker compose version
      register: docker_compose_check
      changed_when: false

    - name: Display docker-compose version
      debug:
        msg: "{{ docker_compose_check.stdout }}"

    - name: Make sure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes
      tags: ['docker']
