---
- name: Deploy Docker Container on EC2 Server
  hosts: aws_ec2
  become: yes
  gather_facts: yes

  vars_files:
    - ec2-vars.yaml

  handlers:
    - name: restart docker
      systemd:
        name: docker
        state: restarted

  tasks:
    - name: Make sure all packages are up to date
      yum:
        name: '*'
        state: latest
        update_cache: yes
      tags: ['packages']
    
    - name: Ensure Docker and Python3 are installed
      yum:
        name: 
          - python3
          - python3-pip
          - docker
        state: present
      tags: ['packages']
    
    # - name: Install Python Docker SDK (required by Ansible)
    #   pip:
    #     name: 
    #       - docker
    #     executable: pip3
    #   tags: ['packages']

   